# prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'flask-app' # For metrics directly exposed by the Flask app
    static_configs:
      - targets: ['flask-app:5000']
    metrics_path: /metrics

  - job_name: 'otel-collector' # For metrics exported by the OpenTelemetry Collector
    static_configs:
      - targets: ['otel-collector:8889']

  # Added job to scrape metrics from Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686'] # Jaeger's admin/query port exposes a /metrics endpoint
    metrics_path: /metrics # Default metrics path for Jaeger
